### ISSUE TITLE
Develop a version suitable for bacteria?

### ISSUE THREAD

**Issue by Dx-wmc** [Kuanhao-Chao/LiftOn#15]
Hey, I am engaged in the analysis of bacterial genomes. Since bacteria do not have introns, bacterial genomes are simpler compared to eukaryotes. Therefore, can software be applied to bacteria? Or can a version suitable for bacteria be developed?

**Comment by Kuanhao-Chao** [comment]
Hi @Dx-wmc,

LiftOn can handle single-exon gene lift-over. You can try running LiftOn and let me know if there are any edge cases that we can improve

Kuan-Hao
