### ISSUE TITLE
What does '-E'/evaluation mode do?

### ISSUE THREAD

**Issue by Andy-B-123** [Kuanhao-Chao/LiftOn#4]
Hi, thank you for this tool and for your  thorough and helpful documentation and examples! 

I'm looking through the options and see the '-E' flag labelled as 'Run LiftOn in evaluation mode'. 

When I try and run this with the examples (eg the HoneyBee one) it produces an error?  eg:

`lifton -g HAv3.1_genomic.gff -o lifton.gff3 -copies ASM1932182v1_genomic.fna HAv3.1_genomic.fna -E`

proceeds to start running normally and then errors at:

```
>> Creating target database :  lifton.gff3
gffutils database build failed with lifton.gff3 cannot be found and does not appear to be a URL
```

Is 'Evaluation mode' more of a testing feature? Thanks!

**Comment by Kuanhao-Chao** [comment]
Hi @Andy-B-123,

Yes, the '-E' flag for 'Evaluation mode' in LiftOn is designed primarily for testing and debugging purposes. It runs the tool in a mode to allow for quicker debugging.

Please simply remove the `-E` argument, and it should work correctly. Please let me know if you encounter any problems. 
Thanks for your feedback! We will update the documentation.
